##docker run -d

##docker run -d --name mysql-atvdocker -p 3307:3306 -e MYSQL_ROOT_PASSWORD=root123 -e MYSQL_DATABASE=atvdocker -e MYSQL_USER=kal -e MYSQL_PASSWORD=123 mysql:8.4

#version: '3.9'
#
#services:
#
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-test
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root123
#      MYSQL_DATABASE: atvdocker
#      MYSQL_USER: kal
#      MYSQL_PASSWORD: 123
#    volumes:
#    - mysql_data:/var/lib/mysql
#
#
#   app:
#      build:
#      container_name: api_atvdocker
#      ports:
#       - "8080:8080"
#       environment:
#           SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/atvdocker?useSSL=false&serverTimezone=UTC&callowPublicKeyRetrival=true
#           SPRING_DATASOURCE_NAME: kal
#           SPRING_DATASOURCE_PASSWORD: 123
#           SPRING_JPA_HIBERNATE_DDL_AUTO: update
#       depends_on:
#         - mysql:
#               condition: service_started  
#
#    volumes:mysql_data
