server:
  port: 8080

spring:
  application:
    name: atvdockerSpring2
  datasource:
    url: jdbc:mysql://localhost:3307/atvdocker?useSSL=false&serverTimezone=UTC&callowPublicKeyRetrival=true
      username: kal
      password: 123
        driver-class-name: com.atvDocker.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
          show-sql: true
          properties:
            hibernate:
              format_sql: true

